application: gps-maps2
version: 1
runtime: python
api_version: 1
default_expiration: "1d"

handlers:

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /svg
  static_dir: svg
  mime_type: image/svg+xml

- url: /images/(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg|ico))

- url: .*/favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static
#  static_files: static/\1
#  upload: static/.*

- url: /admin/.*
  script: admin.py
  login: required

- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /admin.*
  script: gps-admin.py
  login: admin

- url: /bingps.*
  script: gps-bingps.py

- url: /carsico/.*
  script: gps-carsico.py

- url: /benchmark.*
  script: benchmark.py

- url: /debug/.*
  script: gps-debug.py

- url: /api/.*
  script: gps-api.py

- url: /.*
  script: gps-maps.py

admin_console:
  pages:
  - name: Appstats
    url: /stats

derived_file_type:
- python_precompiled

builtins:
- remote_api: on
- datastore_admin: on

#skip_files:
#- ^(.*/)?app\.yaml
#- ^(.*/)?app\.yml
#- ^(.*/)?index\.yaml
#- ^(.*/)?index\.yml
#- ^(.*/)?#.*#
#- ^(.*/)?.*~
#- ^(.*/)?.*\.py[co]
#- ^(.*/)?.*/RCS/.*
#- ^(.*/)?\..*
#- ^(.*/)?utils/.*
#- ^(.*/)?\js/ideas/.*
#- ^(.*/)?\.settings/.*
#- ^(.*/)?\.svn/.*

#error_handlers:
#  - file: default_error.html
#
#  - error_code: over_quota
#    file: over_quota.html
